//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteEarthPhone_Nhom4 {
    
    
    public partial class Homecatetorys {
        
        /// <summary>
        /// HomecatetorysCT1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteEarthPhone_Nhom4.HomecatetorysCT HomecatetorysCT1;
    }
}
